"""Alter column movel_id to imovel_id

Revision ID: 09ade4ae82a4
Revises: 1b5a3109653f
Create Date: 2024-11-20 10:27:59.409833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09ade4ae82a4'
down_revision: Union[str, None] = '1b5a3109653f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fotos_imoveis', sa.Column('imovel_id', sa.Integer(), nullable=False))
    op.drop_constraint('fotos_imoveis_movel_id_fkey', 'fotos_imoveis', type_='foreignkey')
    op.create_foreign_key(None, 'fotos_imoveis', 'imoveis', ['imovel_id'], ['id'], ondelete='CASCADE')
    op.drop_column('fotos_imoveis', 'movel_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fotos_imoveis', sa.Column('movel_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'fotos_imoveis', type_='foreignkey')
    op.create_foreign_key('fotos_imoveis_movel_id_fkey', 'fotos_imoveis', 'imoveis', ['movel_id'], ['id'], ondelete='CASCADE')
    op.drop_column('fotos_imoveis', 'imovel_id')
    # ### end Alembic commands ###
