"""Add imovel_id column to fotos_imoveis

Revision ID: 1b5a3109653f
Revises: 2e4e369aa0cc
Create Date: 2024-11-20 10:24:07.998678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b5a3109653f'
down_revision: Union[str, None] = '2e4e369aa0cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fotos_imoveis', sa.Column('movel_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'fotos_imoveis', 'imoveis', ['movel_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fotos_imoveis', type_='foreignkey')
    op.drop_column('fotos_imoveis', 'movel_id')
    # ### end Alembic commands ###
