"""Criar tabelas iniciais

Revision ID: 2e4e369aa0cc
Revises: 
Create Date: 2024-11-20 10:15:22.325410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e4e369aa0cc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_imoveis', 'fotos_imoveis', type_='foreignkey')
    op.drop_column('fotos_imoveis', 'imovel_id')
    op.alter_column('imoveis', 'numero',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('imoveis', 'descricao',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('imoveis', 'descricao',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('imoveis', 'numero',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('fotos_imoveis', sa.Column('imovel_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_imoveis', 'fotos_imoveis', 'imoveis', ['imovel_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
