"""Add usuario and imovel relationship

Revision ID: 5bee06e5336e
Revises: 7a0860124b43
Create Date: 2024-11-28 14:48:34.208835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bee06e5336e'
down_revision: Union[str, None] = '7a0860124b43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imoveis', sa.Column('usuario_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'imoveis', 'usuarios', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'imoveis', type_='foreignkey')
    op.drop_column('imoveis', 'usuario_id')
    # ### end Alembic commands ###
