"""Add usuario and imovel relationship

Revision ID: 602f8cde6c35
Revises: 89d50a71807f
Create Date: 2024-11-28 14:38:31.981263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '602f8cde6c35'
down_revision: Union[str, None] = '89d50a71807f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
