"""Adiciona novo relacionamento a usuario

Revision ID: 89d50a71807f
Revises: 09ade4ae82a4
Create Date: 2024-11-22 09:59:17.388938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89d50a71807f'
down_revision: Union[str, None] = '09ade4ae82a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imoveis', sa.Column('valor', sa.String(), nullable=False))
    op.add_column('usuarios', sa.Column('telefone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'telefone')
    op.drop_column('imoveis', 'valor')
    # ### end Alembic commands ###
